# Generated by Django 4.0.3 on 2022-07-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "rails_profile_grinding",
            "0002_slm11_06058_slm13_06260_slm15_06262_slm18_09742_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel("SLM01_18045", "SLM01_18045_MDE"),
        migrations.RenameModel("SLM11_06058", "SLM11_06058_MDE"),
        migrations.RenameModel("SLM13_06260", "SLM13_06260_MDE"),
        migrations.RenameModel("SLM15_06262", "SLM15_06262_MDE"),
        migrations.RenameModel("SLM18_09742", "SLM18_09742_MDE"),
        migrations.RenameModel("SLM20_09741", "SLM20_09741_MDE"),
        migrations.RenameModel("SLM26_13996", "SLM26_13996_MDE"),
        migrations.RenameModel("SLM27_14391", "SLM27_14391_MDE"),
        migrations.RenameModel("SLM28_14390", "SLM28_14390_MDE"),
        migrations.RenameModel("SLM29_14389", "SLM29_14389_MDE"),
        migrations.RenameModel("SLM30_14388", "SLM30_14388_MDE"),
        migrations.RenameModel("SLM31_14387", "SLM31_14387_MDE"),
        migrations.RenameModel("SLM32_14386", "SLM32_14386_MDE"),
    ]
