# Generated by Django 4.0.3 on 2022-07-07 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rails_profile_grinding', '0004_alter_slm01_18045_mde_counter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slm01_18045_mde',
            name='p000',
        ),
        migrations.RemoveField(
            model_name='slm11_06058_mde',
            name='p000',
        ),
        migrations.RemoveField(
            model_name='slm13_06260_mde',
            name='p000',
        ),
        migrations.RemoveField(
            model_name='slm15_06262_mde',
            name='p000',
        ),
        migrations.RemoveField(
            model_name='slm18_09742_mde',
            name='p000',
        ),
        migrations.RemoveField(
            model_name='slm20_09741_mde',
            name='p000',
        ),
        migrations.RemoveField(
            model_name='slm26_13996_mde',
            name='p000',
        ),
        migrations.RemoveField(
            model_name='slm27_14391_mde',
            name='p000',
        ),
        migrations.RemoveField(
            model_name='slm28_14390_mde',
            name='p000',
        ),
        migrations.RemoveField(
            model_name='slm29_14389_mde',
            name='p000',
        ),
        migrations.RemoveField(
            model_name='slm30_14388_mde',
            name='p000',
        ),
        migrations.RemoveField(
            model_name='slm31_14387_mde',
            name='p000',
        ),
        migrations.RemoveField(
            model_name='slm32_14386_mde',
            name='p000',
        ),
    ]
