# Generated by Django 4.0.3 on 2022-07-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rails_profile_grinding', '0005_remove_slm01_18045_mde_p000_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_name', models.CharField(max_length=50)),
                ('plant', models.CharField(max_length=50)),
                ('target_process_time', models.FloatField()),
                ('target_grinding_time', models.FloatField()),
                ('target_dressing_time', models.FloatField()),
            ],
        ),
    ]
