from django.db import models


# Create your models here.


class Template(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    size = models.CharField(max_length=20, blank=True, null=True)
    power_z1 = models.TextField(blank=True, null=True)
    power_z2 = models.TextField(blank=True, null=True)
    counter = models.IntegerField(blank=True, null=True)
    main_program = models.CharField(max_length=75, blank=True, null=True)

    p001 = models.FloatField(blank=True, null=True)
    p002 = models.FloatField(blank=True, null=True)
    p003 = models.FloatField(blank=True, null=True)
    p004 = models.FloatField(blank=True, null=True)
    p005 = models.FloatField(blank=True, null=True)
    p006 = models.FloatField(blank=True, null=True)
    p007 = models.FloatField(blank=True, null=True)
    p008 = models.FloatField(blank=True, null=True)
    p009 = models.FloatField(blank=True, null=True)
    p010 = models.FloatField(blank=True, null=True)
    p011 = models.FloatField(blank=True, null=True)
    p012 = models.FloatField(blank=True, null=True)
    p013 = models.FloatField(blank=True, null=True)
    p014 = models.FloatField(blank=True, null=True)
    p015 = models.FloatField(blank=True, null=True)
    p016 = models.FloatField(blank=True, null=True)
    p017 = models.FloatField(blank=True, null=True)
    p018 = models.FloatField(blank=True, null=True)
    p019 = models.FloatField(blank=True, null=True)
    p020 = models.FloatField(blank=True, null=True)
    p021 = models.FloatField(blank=True, null=True)
    p022 = models.FloatField(blank=True, null=True)
    p023 = models.FloatField(blank=True, null=True)
    p024 = models.FloatField(blank=True, null=True)
    p025 = models.FloatField(blank=True, null=True)
    p026 = models.FloatField(blank=True, null=True)
    p027 = models.FloatField(blank=True, null=True)
    p028 = models.FloatField(blank=True, null=True)
    p029 = models.FloatField(blank=True, null=True)
    p030 = models.FloatField(blank=True, null=True)
    p031 = models.FloatField(blank=True, null=True)
    p032 = models.FloatField(blank=True, null=True)
    p033 = models.FloatField(blank=True, null=True)
    p034 = models.FloatField(blank=True, null=True)
    p035 = models.FloatField(blank=True, null=True)
    p036 = models.FloatField(blank=True, null=True)
    p037 = models.FloatField(blank=True, null=True)
    p038 = models.FloatField(blank=True, null=True)
    p039 = models.FloatField(blank=True, null=True)
    p040 = models.FloatField(blank=True, null=True)
    p041 = models.FloatField(blank=True, null=True)
    p042 = models.FloatField(blank=True, null=True)
    p043 = models.FloatField(blank=True, null=True)
    p044 = models.FloatField(blank=True, null=True)
    p045 = models.FloatField(blank=True, null=True)
    p046 = models.FloatField(blank=True, null=True)
    p047 = models.FloatField(blank=True, null=True)
    p048 = models.FloatField(blank=True, null=True)
    p049 = models.FloatField(blank=True, null=True)
    p050 = models.FloatField(blank=True, null=True)
    p051 = models.FloatField(blank=True, null=True)
    p052 = models.FloatField(blank=True, null=True)
    p053 = models.FloatField(blank=True, null=True)
    p054 = models.FloatField(blank=True, null=True)
    p055 = models.FloatField(blank=True, null=True)
    p056 = models.FloatField(blank=True, null=True)
    p057 = models.FloatField(blank=True, null=True)
    p058 = models.FloatField(blank=True, null=True)
    p059 = models.FloatField(blank=True, null=True)
    p060 = models.FloatField(blank=True, null=True)
    p061 = models.FloatField(blank=True, null=True)
    p062 = models.FloatField(blank=True, null=True)
    p063 = models.FloatField(blank=True, null=True)
    p064 = models.FloatField(blank=True, null=True)
    p065 = models.FloatField(blank=True, null=True)
    p066 = models.FloatField(blank=True, null=True)
    p067 = models.FloatField(blank=True, null=True)
    p068 = models.FloatField(blank=True, null=True)
    p069 = models.FloatField(blank=True, null=True)
    p070 = models.FloatField(blank=True, null=True)
    p071 = models.FloatField(blank=True, null=True)
    p072 = models.FloatField(blank=True, null=True)
    p073 = models.FloatField(blank=True, null=True)
    p074 = models.FloatField(blank=True, null=True)
    p075 = models.FloatField(blank=True, null=True)
    p076 = models.FloatField(blank=True, null=True)
    p077 = models.FloatField(blank=True, null=True)
    p078 = models.FloatField(blank=True, null=True)
    p079 = models.FloatField(blank=True, null=True)
    p080 = models.FloatField(blank=True, null=True)
    p081 = models.FloatField(blank=True, null=True)
    p082 = models.FloatField(blank=True, null=True)
    p083 = models.FloatField(blank=True, null=True)
    p084 = models.FloatField(blank=True, null=True)
    p085 = models.FloatField(blank=True, null=True)
    p086 = models.FloatField(blank=True, null=True)
    p087 = models.FloatField(blank=True, null=True)
    p088 = models.FloatField(blank=True, null=True)
    p089 = models.FloatField(blank=True, null=True)
    p090 = models.FloatField(blank=True, null=True)
    p091 = models.FloatField(blank=True, null=True)
    p092 = models.FloatField(blank=True, null=True)
    p093 = models.FloatField(blank=True, null=True)
    p094 = models.FloatField(blank=True, null=True)
    p095 = models.FloatField(blank=True, null=True)
    p096 = models.FloatField(blank=True, null=True)
    p097 = models.FloatField(blank=True, null=True)
    p098 = models.FloatField(blank=True, null=True)
    p099 = models.FloatField(blank=True, null=True)
    p100 = models.FloatField(blank=True, null=True)
    p101 = models.FloatField(blank=True, null=True)
    p102 = models.FloatField(blank=True, null=True)
    p103 = models.FloatField(blank=True, null=True)
    p104 = models.FloatField(blank=True, null=True)
    p105 = models.FloatField(blank=True, null=True)
    p106 = models.FloatField(blank=True, null=True)
    p107 = models.FloatField(blank=True, null=True)
    p108 = models.FloatField(blank=True, null=True)
    p109 = models.FloatField(blank=True, null=True)
    p110 = models.FloatField(blank=True, null=True)
    p111 = models.FloatField(blank=True, null=True)
    p112 = models.FloatField(blank=True, null=True)
    p113 = models.FloatField(blank=True, null=True)
    p114 = models.FloatField(blank=True, null=True)
    p115 = models.FloatField(blank=True, null=True)
    p116 = models.FloatField(blank=True, null=True)
    p117 = models.FloatField(blank=True, null=True)
    p118 = models.FloatField(blank=True, null=True)
    p119 = models.FloatField(blank=True, null=True)
    p120 = models.FloatField(blank=True, null=True)
    p121 = models.FloatField(blank=True, null=True)
    p122 = models.FloatField(blank=True, null=True)
    p123 = models.FloatField(blank=True, null=True)
    p124 = models.FloatField(blank=True, null=True)
    p125 = models.FloatField(blank=True, null=True)
    p126 = models.FloatField(blank=True, null=True)
    p127 = models.FloatField(blank=True, null=True)
    p128 = models.FloatField(blank=True, null=True)
    p129 = models.FloatField(blank=True, null=True)
    p130 = models.FloatField(blank=True, null=True)
    p131 = models.FloatField(blank=True, null=True)
    p132 = models.FloatField(blank=True, null=True)
    p133 = models.FloatField(blank=True, null=True)
    p134 = models.FloatField(blank=True, null=True)
    p135 = models.FloatField(blank=True, null=True)
    p136 = models.FloatField(blank=True, null=True)
    p137 = models.FloatField(blank=True, null=True)
    p138 = models.FloatField(blank=True, null=True)
    p139 = models.FloatField(blank=True, null=True)
    p140 = models.FloatField(blank=True, null=True)
    p141 = models.FloatField(blank=True, null=True)
    p142 = models.FloatField(blank=True, null=True)
    p143 = models.FloatField(blank=True, null=True)
    p144 = models.FloatField(blank=True, null=True)
    p145 = models.FloatField(blank=True, null=True)
    p146 = models.FloatField(blank=True, null=True)
    p147 = models.FloatField(blank=True, null=True)
    p148 = models.FloatField(blank=True, null=True)
    p149 = models.FloatField(blank=True, null=True)
    p150 = models.FloatField(blank=True, null=True)
    p151 = models.FloatField(blank=True, null=True)
    p152 = models.FloatField(blank=True, null=True)
    p153 = models.FloatField(blank=True, null=True)
    p154 = models.FloatField(blank=True, null=True)
    p155 = models.FloatField(blank=True, null=True)
    p156 = models.FloatField(blank=True, null=True)
    p157 = models.FloatField(blank=True, null=True)
    p158 = models.FloatField(blank=True, null=True)
    p159 = models.FloatField(blank=True, null=True)
    p160 = models.FloatField(blank=True, null=True)
    p161 = models.FloatField(blank=True, null=True)
    p162 = models.FloatField(blank=True, null=True)
    p163 = models.FloatField(blank=True, null=True)
    p164 = models.FloatField(blank=True, null=True)
    p165 = models.FloatField(blank=True, null=True)
    p166 = models.FloatField(blank=True, null=True)
    p167 = models.FloatField(blank=True, null=True)
    p168 = models.FloatField(blank=True, null=True)
    p169 = models.FloatField(blank=True, null=True)
    p170 = models.FloatField(blank=True, null=True)
    p171 = models.FloatField(blank=True, null=True)
    p172 = models.FloatField(blank=True, null=True)
    p173 = models.FloatField(blank=True, null=True)
    p174 = models.FloatField(blank=True, null=True)
    p175 = models.FloatField(blank=True, null=True)
    p176 = models.FloatField(blank=True, null=True)
    p177 = models.FloatField(blank=True, null=True)
    p178 = models.FloatField(blank=True, null=True)
    p179 = models.FloatField(blank=True, null=True)
    p180 = models.FloatField(blank=True, null=True)
    p181 = models.FloatField(blank=True, null=True)
    p182 = models.FloatField(blank=True, null=True)
    p183 = models.FloatField(blank=True, null=True)
    p184 = models.FloatField(blank=True, null=True)
    p185 = models.FloatField(blank=True, null=True)
    p186 = models.FloatField(blank=True, null=True)
    p187 = models.FloatField(blank=True, null=True)
    p188 = models.FloatField(blank=True, null=True)
    p189 = models.FloatField(blank=True, null=True)
    p190 = models.FloatField(blank=True, null=True)
    p191 = models.FloatField(blank=True, null=True)
    p192 = models.FloatField(blank=True, null=True)
    p193 = models.FloatField(blank=True, null=True)
    p194 = models.FloatField(blank=True, null=True)
    p195 = models.FloatField(blank=True, null=True)
    p196 = models.FloatField(blank=True, null=True)
    p197 = models.FloatField(blank=True, null=True)
    p198 = models.FloatField(blank=True, null=True)
    p199 = models.FloatField(blank=True, null=True)

    s001 = models.CharField(max_length=50)

    class Meta:
        abstract = True

    def __str__(self):
        return f"{self.timestamp} - {self.main_program_file()} - {int(self.p001)}"

    def main_program_file(self):
        return self.main_program.split("/")[-1].split(".")[0]

    def process_time_in_minutes(self) -> float:
        return self.p006 / 60
